### ISSUE TITLE
5 Digit kB3 Send Error

### ISSUE THREAD

**Issue by jnguyener** [B3-Coin/B3-CoinV2#49] opened 2018-02-07 21:45 UTC
When you are trying to send kB3 you cannot put more than 5 decimals. If you switch it to B3 to send you're able to send more than the 5 decimals.

**Comment by ThunderousDreamer** [comment] 2018-02-07 21:47
duplicate of issue #48

**Comment by despotak** [comment] 2018-02-08 09:00
Closed as it is duplicate of #48 

Thank you both @jnguyener and @ThunderousDreamer for posting this.

**Closed by despotak** 2018-02-08 09:00 UTC
Labels: duplicate
